@base_url=letscountapi.com
@namespace=the-science-guild-counter2

@key=mit-2

### Create Counter
POST https://{{base_url}}/{{namespace}}/{{key}}
Content-Type: application/json

{
  "current_value": 0
}

### Get Counter Value
GET https://{{base_url}}/{{namespace}}/{{key}}

### Increment Counter
POST https://{{base_url}}/{{namespace}}/{{key}}/increment
# POST https://letscountapi.com/the-science-guild-counter/mit-1/increment

### Decrement Counter
POST https://{{base_url}}/{{namespace}}/{{key}}/decrement

### Update Counter Value
POST https://{{base_url}}/{{namespace}}/{{key}}/update
Content-Type: application/json

{
  "current_value": 0
}

### kj
GET https://api.countapi.xyz/create?namespace=the-science-guild-counter&value=42